---
- name: Sync portage repositories
  portage:
    sync: yes

- name: Install portage requirements
  portage:
    package:
      - app-portage/gentoolkit
    state: present

- name: Install packages
  package:
    name:
      - app-admin/sudo
    state: present
