---
- name: Set up Ansible user
  when: user.ansible.setup
  user:
    name: "{{ user.ansible.name }}"
    password_lock: yes
    state: present
    system: no
  register: output_user_ansible

- name: Set up Ansible user SSH config directory
  when: user.ansible.setup
  file:
    path: "{{ output_user_ansible.home }}/.ssh/"
    state: directory
    owner: "{{ user.ansible.name }}"
    group: "{{ user.ansible.name }}"
    mode: 0700

- name: Set up Ansible user SSH keys
  when: user.ansible.setup and user.ansible.public_keys
  loop: "{{ user.ansible.public_keys }}"
  lineinfile:
    path: "{{ output_user_ansible.home }}/.ssh/authorized_keys"
    line: "{{ item }}"
    state: present
    create: true
    owner: "{{ user.ansible.name }}"
    group: "{{ user.ansible.name }}"
    mode: 0600

- name: Set up unprivileged user
  when: user.unprivileged.setup
  user:
    name: "{{ user.unprivileged.name }}"
    state: present
    system: no
  register: output_user_unprivileged

- name: Set up unprivileged user SSH config directory
  when: user.unprivileged.setup
  file:
    path: "{{ output_user_unprivileged.home }}/.ssh/"
    state: directory
    owner: "{{ user.unprivileged.name }}"
    group: "{{ user.unprivileged.name }}"
    mode: 0700

- name: Set up unprivileged user SSH keys
  when: user.unprivileged.setup and user.unprivileged.public_keys
  loop: "{{ user.unprivileged.public_keys }}"
  lineinfile:
    path: "{{ output_user_unprivileged.home }}/.ssh/authorized_keys"
    line: "{{ item }}"
    state: present
    create: true
    owner: "{{ user.unprivileged.name }}"
    group: "{{ user.unprivileged.name }}"
    mode: 0600
