---
- name: Set up Ansible user
  when: "{{ user.ansible.setup }}"
  user:
    name: "{{ user.ansible.name }}"
    password_lock: yes
    state: present
    system: no
  register: output-user-ansible

- name: Set up Ansible user SSH config directory
  when: "{{ output-user-ansible.changed }}"
  file:
    path: "{{ output-user-ansible.home }}/.ssh/"
    state: directory
    owner: "{{ user.ansible.name }}"
    group: "{{ user.ansible.name }}"
    mode: 0700

- name: Set up Ansible user SSH key
  when: "{{ user.ansible.public-keys }}"
  loop: "{{ user.ansible.public-keys }}"
  lineinfile:
    path: "{{ output-user-ansible.home }}/.ssh/authorized_keys"
    line: "{{ item }}"
    state: present
    owner: "{{ user.ansible.name }}"
    group: "{{ user.ansible.name }}"
    mode: 0600

- name: Set up unprivileged user
  when: "{{ user.unprivileged.setup }}"
  user:
    name: "{{ user.unprivileged.name }}"
    password_lock: yes
    state: present
    system: no
  register: output-user-unprivileged

- name: Set up unprivileged user SSH config directory
  when: "{{ output-user-unprivileged.changed }}"
  file:
    path: "{{ output-user-unprivileged.home }}/.ssh/"
    state: directory
    owner: "{{ user.unprivileged.name }}"
    group: "{{ user.unprivileged.name }}"
    mode: 0700

- name: Set up unprivileged user SSH key
  when: "{{ user.unprivileged.public-keys }}"
  loop: "{{ user.unprivileged.public-keys }}"
  lineinfile:
    path: "{{ output-user-unprivileged.home }}/.ssh/authorized_keys"
    line: "{{ item }}"
    state: present
    owner: "{{ user.unprivileged.name }}"
    group: "{{ user.unprivileged.name }}"
    mode: 0600
